### ISSUE TITLE
Update to typescript

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#1]
Not really a story for the user, but more for the developer. Ideally we could update this app to be in Typescript instead of Javascript, but it's a low priority and a slightly ambitious task.

**Comment by benjakugler96** [comment]
hello @brittanyjoiner15. Could I take this one for hacktoberfest?

**Comment by brittanyjoiner15** [comment]
@benjakugler96 so I am a bit conflicted on this for hacktoberfest because I'm worried it's going to be a pain for any pull requests in flight. How long do you think it would take you? If just a couple days then maybe it wouldn't be too terrible. But what do you think? I imagine this is quite a bit of work but maybe it's not that much and could be done quickly and not mess up too many PRs

**Comment by benjakugler96** [comment]
@brittanyjoiner15 if it sounds good to you, we can try to get a pr with basic ts in the next few days and we can merge it on October 1st.

**Comment by brittanyjoiner15** [comment]
@benjakugler96 yeah that sounds good to me!! If we can do that and merge on Oct 1st that would be great!

**Comment by brittanyjoiner15** [comment]
@benjakugler96 actually im sorry - i hate to be so back and forth on this. I am actually leaning towards not making this typescript. My goal has all along been to make this repo very beginner friendly and i worry for folks new to coding making it typescript at the point might introduce new complexity. So I actually want to not do this. 

But i have an idea. What do you think about making a typescript version of the app as is right now and making it a separate repo? So that if someone does want a typescript version of it, that would be available? You could make it under your profile so something like benjakugler96/eui-event-template-ts and then you could have that repo available! I'm not entirely sure exactly how that works for hacktoberfest though. Maybe we keep it in the same repo and have a typescript branch? What do you think?

**Comment by benjakugler96** [comment]
@brittanyjoiner15 What do you think if we hold off until end of October to re-do it in typescript? Many things may change before that and if we have two branches it will be more difficult to maintain (mainly this month which I guess you will get lot of prs 😅)

**Comment by brittanyjoiner15** [comment]
@benjakugler96 i completely agree - let's rediscuss this at the end of October, and if you're still interested then, i'd totally love your help, and if not no worries! Thanks for understanding

**Comment by brittanyjoiner15** [comment]
Closing as i'm unable to maintain this at the moment. Will re-open when i have more bandwidth!
