### ISSUE TITLE
Remove the Extra "Readme" Title in the Readme File

### ISSUE THREAD

**Issue by chiragkhatri19** [brittanyjoiner15/eui-event-template#100]
I was just scrolling through the repo admiring the header I made and saw there are 2 "Readme" title. I thought it's looking odd. So just edited it from my phone.
![IMG_20221012_074801](https://user-images.githubusercontent.com/89431059/195234705-2c863a7a-6cd3-49e0-83b6-fcf6f669cc93.jpg)

**Comment by brittanyjoiner15** [comment]
@chiragkhatri19 this is a good catch! I'll assign you this one.

**Comment by SATYAM1548** [comment]
@brittanyjoiner15 if its open can i work on this

**Comment by brittanyjoiner15** [comment]
@SATYAM1548 this is already assigned, please look for any unassigned issues!
