### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by domstrozynski** [brittanyjoiner15/eui-event-template#105]
Hi, I can translate app into Polish, let me know what's needed ^_^

**Comment by brittanyjoiner15** [comment]
@domstrozynski that would be great, thanks! Assigning you now!

**Comment by domstrozynski** [comment]
@brittanyjoiner15  great! Can you confirm that items from this post https://github.com/brittanyjoiner15/eui-event-template/issues/76 is all that needs to be translated or there's more now?

**Comment by brittanyjoiner15** [comment]
@domstrozynski yes just those items at this point, thanks!
