### ISSUE TITLE
Add lighthouse tool to analyse the repository in terms of performance, accessibility, best practices and SEO

### ISSUE THREAD

**Issue by bpvcode** [brittanyjoiner15/eui-event-template#110]
This feature will allow us to:

* Get a Lighthouse report alongside every PR.
* Prevent regressions in accessibility, SEO, offline support, and performance best practices.
* Track performance metrics and Lighthouse scores over time.
* Compare two versions of your site to find improvements and regressions of individual resources.

We will have local reports for each commit

[Documentation](https://github.com/GoogleChrome/lighthouse-ci)

**Comment by bpvcode** [comment]
@brittanyjoiner15 ,
I will love to implement this one :) Can you assign this to me?

Thanks

**Comment by bpvcode** [comment]
@brittanyjoiner15 ,
Once you are the maintainer of the project, can you please add the labels to this issue?

**Comment by brittanyjoiner15** [comment]
@bpvcode hey this seems like a good idea! I'll assign it to you! thanks for submitting it. will also add some labels.

**Comment by brittanyjoiner15** [comment]
Closing as i'm unable to maintain this at the moment. Will re-open when i have more bandwidth!
