### ISSUE TITLE
renaming the contributor.md file to CONTRIBUTOR.md

### ISSUE THREAD

**Issue by SATYAM1548** [brittanyjoiner15/eui-event-template#112]
for maintaining the consistency of code base .

![image](https://user-images.githubusercontent.com/90546720/196277137-574fbffd-2ca5-466b-a1cf-f0399128b92a.png)

can I edit this brittanyjoiner15

**Comment by SATYAM1548** [comment]
@brittanyjoiner15

**Comment by brittanyjoiner15** [comment]
@SATYAM1548 sure! can you check through all the other existing file names and folders and make any other recommendations for sentencing and structure?

**Comment by SATYAM1548** [comment]
@brittanyjoiner15 
hello!
Yes , I will go through all in a day.

**Comment by brittanyjoiner15** [comment]
@brittanyjoiner15 thanks!

**Comment by SATYAM1548** [comment]
@brittanyjoiner15 
I went over all the files and folders rest all is fine.

**Comment by SATYAM1548** [comment]
@brittanyjoiner15 
code base has no LICENSE file
