### ISSUE TITLE
App crashes when toggling light mode (noticed with Sponsor Section PR)

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#119]
Noticed this in this PR introducing the sponsor section: https://github.com/brittanyjoiner15/eui-event-template/pull/99

For some reason the app crashes when you click on the toggle to change from light to dark and vice versa. I don't see this happening on main, so i think it might be just this branch. 

cc @brandonmcconnell can you add any commentary here on anything you've tried thus far and anything you've ruled out or any hypothesis about anything that was introduced in that PR that could have impacted this or brought it to light if it existed before?

**Comment by brandonmcconnell** [comment]
Sure, I wasn't able to diagnose the issue so far, but I think it may have something to do with the way in which the app re-render occurs at the top-level when switching themes. Though, it could also just be something messed up with my implementation of the sponsor section as well, so definitely check that and don't hold back 🙂

**Comment by adsingh14** [comment]
What I've checked that there's no Sponsor section on live website.

**Comment by brittanyjoiner15** [comment]
@adsingh14 we haven't merged that live into the site yet, if you want to try it out, you'll need to run this branch from this : #99

**Comment by Konzti** [comment]
Hi there, I'd be happy to look into the mentioned bug if still needed. Please let me know.

**Comment by SiddharthaKR** [comment]
Can you assign this to me, would be happy to solve this

**Comment by brittanyjoiner15** [comment]
Hey all, im closing this issue as I'm not able to actively maintain this at this time. Thanks for reaching out!
