### ISSUE TITLE
As a user, I can sort the table by talk date, time, or topic name

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#12]
Right now the table can't be sorted. But it should be fairly straightforward to add sorting to the table. https://elastic.github.io/eui/#/tabular-content/tables#adding-sorting-to-a-table

Ideally, we can sort: 

* session date
* session time
-session name

Any others are a bonus, but not required.

**Comment by ranaDherya** [comment]
hey, @brittanyjoiner15 assign this to me.

**Comment by brittanyjoiner15** [comment]
@ranaDherya you got it!

**Comment by ranaDherya** [comment]
Hi @brittanyjoiner15 ,
I have successfully added sort by date functionality to talks-table. But I want to know how to add multiple sort functions to EuiBasicTable component
`<EuiBasicTable items={this.state.sortedTalks} columns={this.columns} sorting={this.sorting} onChange={this.sortByDateHandler} hasActions />`

This is my sorting object 
` sorting = {
    sort: {
       field: "sessionDate",
       direction: '0',
    },
  };`

**Comment by brittanyjoiner15** [comment]
@ranaDherya hey there! Great progress with this, and that' s really good question! So i believe the sorting object can handle an array of multiple fields, have you tried that? So something like 

```
sorting = { sort: { field: "sessionDate", direction: '0' }, { field: "sessionTime", direction: '0' }, };
```

etc

I haven't actually tried that so im not sure if it works - but have you given that a try? If you have and that doesn't work, let me know and I'll dig into it a bit more

**Comment by ranaDherya** [comment]
Thanks @brittanyjoiner15 , make our sorting object handle an array is working.

**Comment by ranaDherya** [comment]
Found an issue while I was implementing sort by time. When we change the time to local and to EDT. It is only changing the time not the date.
 for eg:- `{
    sessionDate: "Sept 13th",
    sessionTime: "2022-09-13T23:40:00.000Z",
    title: "Star Wars vs Star Trek",
    description:
      "Learn why Star Wars is more super than Star Trek because of beets, bears, and battlestar galactica.",
    genre: "Arts",
    speaker: [findSpeaker("Dwight Schrute")],
  },` 
here time is 23:40,
Now when I change it to local time i.e IST it should become 5:10 and date should change to next date, but only time is changing while the date remains the same.

**Comment by brittanyjoiner15** [comment]
ah @ranaDherya yeah that's a good point. feel free to leave off sorting by time in this one, and i can create an issue to update the time change function to update the entire date and we'll add in sorting by time after that!

**Comment by ranaDherya** [comment]
ok sure

**Comment by ranaDherya** [comment]
Hi @brittanyjoiner15, the logic to sort by time is still there I just comment the option  for user to sort by Time. Once the time-zone issue is solved, we can just remove that comment and it should also work for time.

**Comment by brittanyjoiner15** [comment]
@ranaDherya i'm reassigning as it's been over two weeks since an update on the PR. Feel free to comment back in here if you're still working on it and i can assign to you again if it's available.

**Comment by raghavpatidar** [comment]
Please assign this to me since I would really like to work on it.

**Comment by brittanyjoiner15** [comment]
@raghavpatidar assigning you now! please add a comment every couple of days to let me know you're progress on it!

**Comment by sathiyaIbe** [comment]
Assign this issue to me I will solve this as soon as possible

**Comment by brittanyjoiner15** [comment]
@sathiyaIbe im so sorry, im unable to actively monitor this repo at the moment, so i can't promise how quickly i'd be able to review a PR for this. if you are still interested in a month or so, feel free to check back in! sorry about that

**Comment by brittanyjoiner15** [comment]
Closing as i'm unable to maintain this at the moment. Will re-open when i have more bandwidth!
