### ISSUE TITLE
Social icons need to be centered in bottom bar/footer

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#120]
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/16166290/198670639-642589b1-4616-4bc4-94a9-6910cd267d74.png">

I feel like the social icons should be shifted to the left a bit to not look off center from the content above.

**Comment by chiragkhatri19** [comment]
I'll do it brittany, Please assign me this one

**Comment by adsingh14** [comment]
It's because of `CSS flexbox` though.

**Comment by chiragkhatri19** [comment]
> It's because of `CSS flexbox` though.

I'll try to fix it, If I need any help I'll tell you 
!
