### ISSUE TITLE
Home page content is not centred on mobile view.

### ISSUE THREAD

**Issue by adsingh14** [brittanyjoiner15/eui-event-template#127]
I checked the home page on mobile and found asymmetrical header buttons (schedule and theme switcher).

![untitled.jpg](https://user-images.githubusercontent.com/35252877/198890583-731a007c-c093-4689-bacf-f9c7f0e3b734.jpg)

- Any views on center align all buttons on header option ? (Optional)
- Apart from that, homepage schedule buttons needs to be center.

**Comment by MaximSamorukov** [comment]
@brittanyjoiner15 can I take this issue?

**Comment by brittanyjoiner15** [comment]
@MaximSamorukov sure! assigning you now.

**Comment by MaximSamorukov** [comment]
@brittanyjoiner15 Thanks

**Comment by brittanyjoiner15** [comment]
Closing as i'm unable to maintain this at the moment. Will re-open when i have more bandwidth!
