### ISSUE TITLE
The toggler is a bit inaccurate

### ISSUE THREAD

**Issue by MaximSamorukov** [brittanyjoiner15/eui-event-template#129]
It seems to me that the toggler is a bit inaccurate. The gap between the round element and the top edge is smaller than the bottom corresponding gap. Can I try to fix it?

![image](https://user-images.githubusercontent.com/53444059/207541791-2b39592b-194a-448f-a735-c0ae545cfd89.png)

**Comment by brittanyjoiner15** [comment]
Closing as i'm unable to maintain this at the moment. Will re-open when i have more bandwidth!
