### ISSUE TITLE
As a user, I can access the different tabs by route

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#13]
Add a router so that going to `/talks` displays the talks component, `/speaker`, etc and clicking on the logo takes you back home.

I'm leaning towards React Router, or Hook Router, but if you know of another alternative, I'm open to it!

**Comment by iFrogHop2Worlds** [comment]
Could you assign me this?

**Comment by brittanyjoiner15** [comment]
@iFrogHop2Worlds yes! assigning now!

**Comment by iFrogHop2Worlds** [comment]
Awesome thanks. I have finished the task here https://github.com/iFrogHop2Worlds/eui-event-template 
Ill make the pr on Oct 1st  if you don't mind :)

**Comment by brittanyjoiner15** [comment]
@iFrogHop2Worlds yep that's fine!
