### ISSUE TITLE
As a user, I can create an issue to request a feature request from a template

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#16]
Create an issue template so that when someone comes to this repo to file a bug or request a feature, they can choose from an issue template for a feature request.

Please use the checklist from the items in the [contributing guidelines](https://github.com/brittanyjoiner15/eui-event/blob/main/contributing.
md) to create sections of an issue for each bullet point. Ie, the bug template should have checklist / sections for submitting:

* Describe the ideal state of what the feature would do in one sentence. (Use language like "As a user, I can ....")
* Explain in more detail what that might look like.
* Add a link to any examples that you can share that demonstrate this feature.
* Bonus points if you can also explain how to implement this!

Here's the docs explaining how to do it: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

**Comment by brittanyjoiner15** [comment]
@divyanshraj0408  adding you to this one!

**Comment by divyanshraj0408** [comment]
@brittanyjoiner15 Thanks for adding me.

**Comment by brittanyjoiner15** [comment]
@divyanshraj0408 hey there! have you had a chance to work on this?

**Comment by divyanshraj0408** [comment]
Yes I am working on it, will make the PR asap.

**Comment by brittanyjoiner15** [comment]
@divyanshraj0408 great, thanks!
