### ISSUE TITLE
Review contributing guidelines

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#18]
Review [Contributing Guidelines](https://github.com/brittanyjoiner15/eui-event/blob/main/contributing.md) and fork a repo. Make suggestions to the docs about troubleshooting any issues you come across, or clarify any language that doesn't make sense. (Feel free to comment on here and ask for clarification on something, then take what you learn and update the markdown file).

**Comment by diegoherrer4** [comment]
I'd love to work on this if that's okay

**Comment by brittanyjoiner15** [comment]
Yes @diegoherrer4 go for it!

**Comment by brittanyjoiner15** [comment]
Yes @diegoherrer4 go for it!
