### ISSUE TITLE
As a user, I can create an issue to file a bug from a template

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#2]
Create an issue template so that when someone comes to this repo to file a bug or request a feature, they can choose from an issue template for a new bug. 

Please use the checklist from the items in the [contributing guidelines](https://github.com/brittanyjoiner15/eui-event/blob/main/contributing.md) to create sections of an issue for each bullet point. Ie, the bug template should have checklist / sections for submitting: 

- Explain the bug and WHERE you saw it (the page, section on the page)
- Also explain what you expected to happen
- Describe how we can reproduce it
- Note your browser and device
- Bonus points if you can share a screenshot or recording!

Here's the docs explaining how to do it: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository

**Comment by divyanshraj0408** [comment]
Hey! I would like to contribute to this issue during HacktoberFest.

**Comment by brittanyjoiner15** [comment]
@divyanshraj0408 sounds great! If you can just comment on here every couple of days to let me know any progress/updates/that you're interested, that would be great! Assigning you now.

**Comment by divyanshraj0408** [comment]
Do we want separate templates for bugs and feature request or in the same file?

**Comment by brittanyjoiner15** [comment]
@divyanshraj0408 I think separate issue types but what do you think?

**Comment by brittanyjoiner15** [comment]
@divyanshraj0408 I think separate issue types but what do you think?

**Comment by divyanshraj0408** [comment]
Yes, I was thinking the same as it will make the process of reporting issue much easier. 
Will make the PR as soon as October starts.

**Comment by brittanyjoiner15** [comment]
Sounds good!

**Comment by brittanyjoiner15** [comment]
@divyanshraj0408 want me to add you to the [issue for the feature request template](https://github.com/brittanyjoiner15/eui-event-template/issues/16) as well? Not sure if you were planning to make both templates or just the bug one.

**Comment by divyanshraj0408** [comment]
Oh I actually didn't notice. Yes it would be awesome if I will be assigned for the feature request template also.

**Comment by brittanyjoiner15** [comment]
Oddly it won't let me assign you to it haha, i think it needs you to comment on it, so if you can comment over there, then i can assign it!

**Comment by brittanyjoiner15** [comment]
@divyanshraj0408 perfect! thanks!
