### ISSUE TITLE
As a user, I can update a Google Sheet with talk info

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#20]
Similar to https://github.com/brittanyjoiner15/eui-event/issues/19, but for the talks and not the speakers. Instead of cards, each row on the Google Sheet will create a new row in the EuiTable. 

The spreadsheet columns should contain: 

* session date and time (in standard ISO timestamp format)
* talk title
* talk description
* genre (one string)
* speaker

And the app is updated to create an EuiTable with items from the Google Sheet.

As part of this issue, please update the documentation on the readme for how to run this locally and any necessary steps to configure and hook up your own spreadsheet.

Also, it is a requirement to keep the formatting styles, ie, still able to change the date/time, badges for genre, and speaker avatars and name shown in the speaker column.

This might also help : https://dev.to/varshithvhegde/easy-way-to-create-your-own-api-for-free-1mbc

**Comment by PrathamGwari** [comment]
Hi @brittanyjoiner15 , the issue looks interesting to work on. Can you please assign this issue to me. 

I want this to be part of my contribution to hacktoberfest 2022, so can I generate a pull request in October?

**Comment by brittanyjoiner15** [comment]
@PrathamGwari same note as the other issue - this all sounds good, thanks for your help! Please just comment in here every couple or days or so, so that i know you're still working/interested in it!

**Comment by PrathamGwari** [comment]
Thanks a lot @brittanyjoiner15

**Comment by brittanyjoiner15** [comment]
thank YOU!

**Comment by brittanyjoiner15** [comment]
@PrathamGwari just want to confirm you're still interested in this correct?

**Comment by PrathamGwari** [comment]
> @PrathamGwari just want to confirm you're still interested in this correct?

Yes I am will start work soon

**Comment by brittanyjoiner15** [comment]
@PrathamGwari Sounds good! Thanks for the quick response!

**Comment by brittanyjoiner15** [comment]
@PrathamGwari are you still planning to work on this one as well to be like the Speaker Info tab?

**Comment by PrathamGwari** [comment]
> @PrathamGwari are you still planning to work on this one as well to be like the Speaker Info tab?

Yes I am still willing to work on this issue.

**Comment by PrathamGwari** [comment]
@brittanyjoiner15 can you have a look at this. 

https://drive.google.com/file/d/1JwU9SBdsTQ6xRwtqOxPx4iRtNL6gAxNx/view?usp=sharing

Is the date fine or I have to format it to show month name?

**Comment by brittanyjoiner15** [comment]
@PrathamGwari that looks awesome! I think the format is fine, if you can just check that it doesn't break anything with the time zone conversion, but I think that's just on the session timestamp field - although i believe we pass it a whole timestamp string with date, so we might need to check that function still works with receiving the data like this. But as long as that works for session time that's fine, I'm not too worried about the month formatting of the date, although might address that later in another issue. You've done so much already though this is great!!

**Comment by PrathamGwari** [comment]
https://user-images.githubusercontent.com/75363815/194228691-b73718a2-ead5-489c-a0ca-417383b7e748.mp4

@brittanyjoiner15 I think the timezone feature is working fine too, will open a pull request soon.
