### ISSUE TITLE
Create a checklist for items someone should update if they want to customize this for their event.

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#21]
Fill out this markdown file with a checklist of sections to go to in the app to update if you use this repo as a template. Ie, speakers, talks, site title, etc. 

Bonus points if you can actually link to the line(s) that need to be updated for that section!

**Comment by shahx95** [comment]
Hi, @brittanyjoiner15. I'd like to take this up.

**Comment by brittanyjoiner15** [comment]
@shahx95 awesome! assigning to you now!
