### ISSUE TITLE
Speaker column on Talks tab accepts multiple speakers

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#22]
Make it so that if there is more than one speaker, both can be displayed and it wraps nicely. 

Cheat code: I actually already did this for my repo, and unless the table changes a lot before this issue is tackled, you can probably mostly copy and paste what I did here :) 

https://github.com/brittanyjoiner15/rainbowstack-summit/blob/master/src/components/panels/TalksPanel.jsx#L49-L77
and also 
https://github.com/brittanyjoiner15/rainbowstack-summit/blob/495dac0ca3eea06b253faa319143d726bb2d7dde/src/components/panels/TalksPanel.jsx#L134

Let me know if you need any help!

**Comment by Vinitvh** [comment]
Hi, can I work on this?

**Comment by brittanyjoiner15** [comment]
@Vinitvh Yes! Just assigned you!

**Comment by Vinitvh** [comment]
@brittanyjoiner15 EuiFlexGroup aligns speakers vertically but there seems to no option to change EuiFlexItem flex direction to row, which is by default column that aligns avatar and name vertically. Do you want me to write a custom class for it? Need some help here. 
![eui-col](https://user-images.githubusercontent.com/42197888/190870444-a909ae85-36fe-4d8e-9f22-96a06e5ce829.png)

**Comment by brittanyjoiner15** [comment]
@Vinitvh I'm afk but will be back to my computer soon to help triage better- but in the meantime I think I linked to an example of how I did this in my rainbowstack-summit repo. Did you get a chance to look at that?

**Comment by Vinitvh** [comment]
Yes, In your example too the speakers gets aligned horizontally. For two it may look okay but as we add more it gets messy. I think it looks better if speakers are  vertically aligned.

**Comment by brittanyjoiner15** [comment]
@Vinitvh ah okay i see what you're saying now, that's a good point! Could you set the `EuiFlexGroup` to display as a row? Check out the props here: https://elastic.github.io/eui/#/layout/flex#flex-group-is-for-a-single-row-layout

You can pass `EuiFlexGroup`  a `direction="row"` prop

**Comment by brittanyjoiner15** [comment]
Resolved with https://github.com/brittanyjoiner15/eui-event-template/pull/23
