### ISSUE TITLE
[HELP] Add Code of Conduct to Repo

### ISSUE THREAD

**Issue by kjaymiller** [brittanyjoiner15/eui-event-template#24]
Adding a Code of Conduct to the repo would help contributors know that a standard of conduct is set and that they should feel more welcome to contribute.

**Comment by brittanyjoiner15** [comment]
@kjaymiller do you have any particularly good examples you've seen of repos that do this? never made one before so want to look around! I can search if nothing comes to mind for you but didn't know if you had any that you prefer!

**Comment by kjaymiller** [comment]
Most of my current repos have one. I also have a [template tool for VSCode](https://marketplace.visualstudio.com/items?itemName=kjaymiller.vscode-add-code-of-conduct) that let's you choose from popular templates. You can save your code of conduct at the root or in `.github` as `CODE_OF_CONDUCT.md`

**Comment by brittanyjoiner15** [comment]
@kjaymiller this extension is awesome!!
