### ISSUE TITLE
Change title in header and hero image on Event Details panel

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#29]
Change the title and hero image to be something more generic. Feel free to have a little fun with it and think of something that relates more to our "fun" speakers :) 

This will be more a creative task! Please create an image and add it to the images folder, and then [replace the current hero image here](https://github.com/brittanyjoiner15/eui-event-template/blob/88b197cafa0ab3454e38aa31e10e043496c568ba/src/components/panels/EventDetails.jsx#L18).

Title is set here: https://github.com/brittanyjoiner15/eui-event-template/blob/88b197cafa0ab3454e38aa31e10e043496c568ba/src/components/Navbar.jsx#L13

**Comment by camillet16** [comment]
Hi there! I'd like to be assigned to this :) but would also like to know more about what you mean by 'generic'. Would you like something Parks and Recreation related? XD

**Comment by brittanyjoiner15** [comment]
@camillet16 yes happy to assign to you! And yes i basically just mean something that's not an actual event (rainbow stack summit is the event i planned that this template was based off of!). If can you think of something that would combine the Office and Parks and Rec that would be really fun _(maybe something like "Best TV Characters Conference"... or something shorter lol)_, but if not feel free to just stick with Parks and Rec! Have fun with it!

**Comment by brittanyjoiner15** [comment]
@camillet16 also let me know if you need access to something like Canva. I believe I have a spot on my account and i can temporarily assign it to you if you need something to help design an hero image.

**Comment by camillet16** [comment]
@brittanyjoiner15 Hahahaha! got it,  thanks for the info. I'm all sorted on design resources but thank you kindly for the canva offer. 😄 Happy hacktober!

**Comment by brittanyjoiner15** [comment]
@camillet16 awesome!! excited to see what you come up with, and thanks again for the help! Just let me know if you have any questions!
