### ISSUE TITLE
Change the text in the footer

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#30]
Instead of referencing Elastic and rainbowstack ERG, change this text to be something else. Have a little fun with it and make it something fictional that goes along with our theme of our speakers
![](https://user-images.githubusercontent.com/16166290/192348302-eb15367f-2c7c-4541-aa32-3bedc492983c.png)

**Comment by Arnav-Negi** [comment]
Hi! I'm participating in Hacktoberfest 2022 and would like to contribute to this issue. Can you assign it to me?

**Comment by brittanyjoiner15** [comment]
@Arnav-Negi yes!

**Comment by Nishant891** [comment]
Hey! I would like to contribute on this issue.

**Comment by brittanyjoiner15** [comment]
@Nishant891 appreciate the interest, but this has already been assigned! You're welcome to reach out to the assignee and pair with them, or take a look at our other open issues that have not been assigned! If you don't see any, i'm adding new ones as I think of them, so keep checking back!

**Comment by Nishant891** [comment]
Okay I understand.
