### ISSUE TITLE
Click on logo to go to the Event Details panel

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#31]
When clicking on the logo in the top left, a user is returned to the Event Details panel. 

![](https://user-images.githubusercontent.com/16166290/192379001-7ddbe709-64f2-406f-899a-f9b248f01752.png)

When clicking on that icon, you go to this tab: 
![](https://user-images.githubusercontent.com/16166290/192380856-18a51463-8cf4-46c5-b3e8-ab4aa393c7d8.png)

**Comment by benjakugler96** [comment]
Hello. Raising a PR for this. Trying to find how to add cursor pointer to header logo but it seems that passing `iconProps={{ style: { cursor: "pointer" } }}` is not working. I can raise another pr for that once I find the solution

**Comment by binnyle** [comment]
Hi @brittanyjoiner15, I think we can change tab by passing down selectedTab and change it to the first tab onClick, I would love to work on this. 

Thanks!

**Comment by brittanyjoiner15** [comment]
@benjakugler96 hey there, appreciate the enthusiasm, but per the guidelines, you need to pick an issue and be assigned it before creating a pull request. I will allow it this time though and I'll update the guidelines to make that more clear.

**Comment by brittanyjoiner15** [comment]
@BinniesLite sorry Benja claimed this one, but feel free to check out some of the other issues, or if you have some other ideas for how to improve the app, create your own issue and I'll review it and can assign to you!
