### ISSUE TITLE
Create a tab for watching recordings of talks

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#32]
Create a page that people can embed youtube videos on to show talks after the conference. 

Ideally it would be a page with two columns with embedded youtube videos.

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Can I take this one? 😃

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell i appreciate your enthusiasm but i prefer folks take one issue at a time. Once you complete you the issue, you're welcome to pick another one! So I'll hold off on assigning this for now in case someone else wants to take it while you're working on the other one, but once your other is merged, you're welcome to comment in here and request again!

**Comment by Vaani-pathariya** [comment]
Hello @brittanyjoiner15 ! I am new to open source and know the basic front end(Html ,CSS,Javascript) along with a little bit of react .Can I contribute to this one ?

**Comment by brittanyjoiner15** [comment]
@Vaani-pathariya yeah feel free to! It doesn't have to be anything fancy, and Eui components are very easy to work with, so i think you can definitely handle it! If you need any help just reach out. 

What I would recommend is [creating another tab ](https://github.com/brittanyjoiner15/eui-event-template/blob/8cefe4c73b1dea7f5fa33c6bd15071cb1bbae463/src/components/MainPage.jsx#L36) for `recordings`, and then copy one of the formats of the other panels (maybe the speaker one?) and you can use EuiCards to hold videos. I would try to maybe only do 2 columns instead of 3 like we have for speakers.

Let me know if that makes sense or if you'd like more direction!

**Comment by Vaani-pathariya** [comment]
I created the basic layout for the recordings tab . It currently shows the same data as of the speakers tab since right now i didn't know what all you want within each card. Please guide me with the same and i will do the required 
<img width="936" alt="image" src="https://user-images.githubusercontent.com/94799887/193249016-44af80ea-2f98-41bb-a09d-be6be8edbf5e.png">

**Comment by brittanyjoiner15** [comment]
@Vaani-pathariya that looks great! Can you populate it with some videos from youtube? Maybe like 6 videos with clips from the office and parks and rec tv shows?
