### ISSUE TITLE
Add an FAQ tab

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#34]
Create a tab with some lorem ipsum text with FAQs about the conference/event.

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 I'd like this one!

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell will add you to this one!!

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Thanks! Do you know offhand if any of your components support a type of Toggle/Accordion functionality I could use for the FAQ functionality, or if I should set that up anew?

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell i know that Eui has a toggle (and accordion i believe), as far as components I've currently got I don't think i have anything configured for one. How are you imagining needing one? Like FAQ would toggle on or off?

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 I was thinking the questions themselves could toggle their answers.

Functional inspiration: https://www.awwwards.com/faqs/

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell oooh that's really cool, i like that idea a lot actually. Eui definitely has this functionality! https://elastic.github.io/eui/#/layout/accordion

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Awesome, thanks! I'll wait till October hits and then get started on this 🥳

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell feel free to start now and i can just wait til oct 1st to merge if you'd like!

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Oh great, thanks!

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell hey there! have you had a chance to work on this?

**Comment by brandonmcconnell** [comment]
Yup! I started it, and I'll try to get something up and ready by EOD Tuesday :)

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell sounds good!

**Comment by brandonmcconnell** [comment]
Btw @brittanyjoiner15 is there already a ticket created for the routing, so the address bar matches the current tab `id`? If not, I'd be happy to take that one and tackle it next week.

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell there is not another ticket for the routing so if you can set up a route for this tab as part of this issue, that would be great!

**Comment by brandonmcconnell** [comment]
I just realized the live app already does the routing, but I don't see that behavior when running it locally. It probably already works using the `id` of each tab, so there shouldn't be anything left to do there, unless there's another file outside of MainPage where I need to account for that.

Let me know! 🙂

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell sorry i should clarify, there IS an issue for the routing, but not for automatically adding new pages to the routing! Try pulling from `main` and you should see the routing! I've merged several PRs today, one of which includes the logic for routing that you can use!

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell here's the routing changes that you should see from `MainPanel` when you pull locally! https://github.com/brittanyjoiner15/eui-event-template/blob/aaf3246cc182dc2800b86d7701a31082a36e52ca/src/components/MainPage.jsx#L70

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Thanks! Yep, I see that and made the change. I was on a generated copy of the repo rather than a fork, so I switched to a fork so I can sync changes now 👏🏼

**Comment by brandonmcconnell** [comment]
Btw any chance we could update EUI to the latest version? There have been several improvements made for responsive logic, including a few new hooks I'd like to use from a newer version.

I tried updating locally but ran into some peer dependency errors.

**Comment by brandonmcconnell** [comment]
If it's too much trouble — no worries. I'm adding a `hooks` directory with a custom hook that wraps the `useIsWithinBreakpoints` hook included in the current version this template uses.

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell i actually just about to make an issue for upgrading Eui as I agree, it's probably a good time to do that. If you think it makes sense to be part of this PR, feel free to go for it, but i am also good with the setup you've got and then we can make a new issue for updating Eui and address that in another PR. Would you like to be assigned that issue?

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Absolutely! Responded with more thoughts in the PR (#66). Thanks!
