### ISSUE TITLE
Add social links to footer

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#35]
Update the footer with icons for Facebook, Twitter, LinkedIn, and Instagram and make them linkable (you can just link to "#" for now), so that if someone wants to use the template, they can include links to their events social profiles

**Comment by laxmanbalaraman** [comment]
Hey @brittanyjoiner15! I think I can do this one. Can you assign this to me?

**Comment by brittanyjoiner15** [comment]
@laxmanbalaraman yep will do!

**Comment by akshitsangwan** [comment]
Hey @brittanyjoiner15, I am also interested to show my version of the footer design. Can you assign me this task?

**Comment by brittanyjoiner15** [comment]
@akshitsangwan this has already been assigned to @laxmanbalaraman but if you want to raise another issue with your ideas for footer improvements, feel free to create an issue and I'll review it and can assign it to you!

**Comment by akshitsangwan** [comment]
Okay @brittanyjoiner15, will do it! Thanks for this:)

**Comment by laxmanbalaraman** [comment]
Hey @brittanyjoiner15 ! I have added the social icons to the footer. The icons are responsive even in the mobile version. I made the icons colorful so they match the rainbow theme however feel free to change them. Tell me if everything looks fine :).

PS: Also I noticed that the footer text is not aligned to the center in the mobile version (you can see that in the second image). I didn't fix that coz it's not part of my issue. However, if u want I can fix them in this issue, or more appropriately create a new issue and fix them.

![footer icons](https://user-images.githubusercontent.com/67074796/193208614-0b1a932d-af58-432d-8a86-a9bf290d1b1f.jpg)
![responive icons](https://user-images.githubusercontent.com/67074796/193208633-b9521e62-e982-434f-b72d-ac70d9110c38.jpg)

**Comment by brittanyjoiner15** [comment]
This looks awesome! We have some other issues to move away from the rainbow theme, but i still like the colorful icons!! Those are perfect! This looks good to go!

And good catch on the center alignment. Would you actually mind to create that issue and then I'll assign it to you and you can fix it in a separate PR?

**Comment by laxmanbalaraman** [comment]
> And good catch on the center alignment. Would you actually mind to create that issue and then I'll assign it to you and you can fix it in a separate PR?

Sure! I will create a new issue for that. 
Thanks!!
