### ISSUE TITLE
Create a registration form that sends responses to a Google Sheet

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#36]
Create a registration form that collects name and email, and send those responses to a Google Sheet. 

As part of this, you'll need to update the documentation to explain how someone using this repo as a template can then hook up their own GoogleApi and Google Sheet to this.

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Does your org already have an API active and ready to use with the Sheets API for this task?

**Comment by iFrogHop2Worlds** [comment]
assign me please @brittanyjoiner15

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell great questions! No we don't, so this is a bit of a big one. Although @PrathamGwari is working on this for speaker and talk tabs, so it might be worth coordinating with him for whoever grabs this.

**Comment by brittanyjoiner15** [comment]
@iFrogHop2Worlds i see you're assigned to [this issue](https://github.com/brittanyjoiner15/eui-event-template/issues/13), and we typically prefer people only being assigned one issue at a time unless they're extremely related issues. Once you finish your other issues and that is merged, you're welcome to come back and request this one!

**Comment by SahilAnower** [comment]
@brittanyjoiner15 Can I work on this? Seems Interesting

**Comment by brittanyjoiner15** [comment]
@SahilAnower yes! assigning you now. You might want to coordinate with @PrathamGwari on https://github.com/brittanyjoiner15/eui-event-template/issues/19 and see if you can both maybe use the same Google Sheets API and perhaps do all of this in the same google sheet?

**Comment by SahilAnower** [comment]
Thanks a lot @brittanyjoiner15

**Comment by SahilAnower** [comment]
![Screenshot 2022-09-28 at 19-59-07 Eui and React Event Site Template](https://user-images.githubusercontent.com/49086583/192806589-5df4b5b4-f8aa-4be2-93f4-67827caf8db9.png)
![Test Sheet - Google Sheets — Mozilla Firefox 9_28_2022 8_00_15 PM](https://user-images.githubusercontent.com/49086583/192806837-3bec43fd-03b0-4f5a-a871-f95068ad591a.png)
I have currently done this, using sheetdb api rather than google sheet api. Looking forward to transfer the same for sheet one.

**Comment by brandonmcconnell** [comment]
@SahilAnower Awesome resourcing! I'm eager to see your implementation once it's merged in 🙌🏼

**Comment by brittanyjoiner15** [comment]
@SahilAnower oh nice! that is so fast and exactly what im looking for!

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell check out what @PrathamGwari has done in this PR: https://github.com/brittanyjoiner15/eui-event-template/pull/58 . Feel free to utilize something similar, although admittedly will be different as this is meant to go the other way - ie, FROM website TO google sheet. But if we can keep it in the same sheet that would be great, but not necessary

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Is there more Google-Sheets-related work to be done? Or do you mean for my own personal research?

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell oh saw your comment about wanting to see his implementation, and also thought you were assigned to this issue but just realized @SahilAnower is assigned to this so sorry!

@SahilAnower please check out what @PrathamGwari has done in this PR: https://github.com/brittanyjoiner15/eui-event-template/pull/58 and feel free to try to utilize something similar, but it's okay if it needs to be in another sheet!
