### ISSUE TITLE
Create a file listing contributors

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#39]
I'd love to recognize contributors who have PRs merged in this Repo!

Create a new file called `contributors.md` and make a nice page that shows the usernames of folks who have merged PRs. (You can [find all those here](https://github.com/brittanyjoiner15/eui-event-template/pulls?q=is%3Apr+is%3Aclosed).)

Please look at some examples of other repos that do this and help come up with a nice way to make that page that is more than just a bullet point of names. Maybe we want to format in a table? Maybe we link to their profile as well?

BONUS points if you can make it so that the file is updated with the contributors name with each PR request.

**Comment by ArshErgon** [comment]
assign it to me.
I will do some research on this about how to style them nicely.
okay, so you want a script which will update the `contributor.md` file whenever someone do a PR, but what if someone's PR is not related to the issue? will it be still count? it will be done soon.

**Comment by brittanyjoiner15** [comment]
@ArshErgon great thank you! assigning you now.

And yes the script would be great - i think it doesn't necessarily have to be tied to the issue. I was not exactly imagining a history/changelog type of thing, although that might not be a bad idea if you recommend that! Just basically something that provides some recognition of all these folks who do create PRs. It should generally be tied to an issue but in case it's not, that's fine. 

One thing that might be tricky - ideally it only mentions someones github username ONCE, so if you have multiple contributions, it doesn't add a new line with your github username with each PR. So the script would need to check and see if the name is in there, and if not add it. (I imagine that wouldn't be terribly hard to implement but also I've never built something like this so maybe it is!)

**Comment by ArshErgon** [comment]
> (I imagine that wouldn't be terribly hard to implement but also I've never built something like this so maybe it is!)

Touch wood, neither I, there's a data structure called a 'set' I'd use it for checking the duplicates(PS: sets hates duplicates, they automatically removes them),  but I have to put names list in two, one in contri.md and other one in my script for checking. Umm, it would be amazing to solve this.

**Comment by brittanyjoiner15** [comment]
@ArshErgon yeah!! if you make a solution for this you should totally make it a package that others can add to their projects - i imagine a lot of open source maintainers would find it helpful! I wonder if something exists already? I haven't done much research admittedly

**Comment by ArshErgon** [comment]
ummm, something similar, not replica not similar of what we want https://github.com/mntnr/name-your-contributors 
I never made packages, lets see where this PR will take me.

**Comment by brittanyjoiner15** [comment]
@ArshErgon ah interesting! yeah that looks like in the same area of what I'm hoping for, but maybe a bit more than i want. 
And yeah, have fun with it! Feel free to be creative and have fun with it! You can put as much or as little as you want into it. If you want to make a package, that's awesome, if you just want to add a file and list the contributors we've had so far and help update the PR template to add a checklist item for people to add their username to that file if it's their first time contributing, that's cool too! Totally up to you.

**Comment by brittanyjoiner15** [comment]
@ArshErgon hey there! just wanted to check and see if you're still working on this?

**Comment by ArshErgon** [comment]
Hey @brittanyjoiner15 I haven't started working on this because I was working on many other open source projects, I will be doing it today, but I done research, I think the script could be possible with GitHub api, the APIs token_key will be generated by you(public key), the key will help us to get pull_request made by people, and it will be a full link, after storing the link, we could split the link and get the username of the user, and add that username with the profile like ex: `https://www.github.com/{username}`.

**Comment by brittanyjoiner15** [comment]
@ArshErgon thanks for your contribution!
