### ISSUE TITLE
Create a md file to track research

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#42]
Sometimes we'll have tasks where want to research certain things, like new technology we might want to add in the app. 

Create a file that we can organize any notes from these research separately from actually taking actions on the research. 

Spend a few minutes doing a little research to see if anyone else is doing something like this and maybe get some ideas for how to structure it, but if there are no other ideas, simply create a file called `research-notes.md` and add it to the `docs` folder.

**Comment by Mannuel25** [comment]
Hello @brittanyjoiner15 , I'd love to take this up for hacktoberfest. Could you please assign it to me once the event commences?

**Comment by brittanyjoiner15** [comment]
@Mannuel25 yes! ill assign it now. if you want to get the PR ready i can wait until Oct 1st to merge it!

**Comment by Mannuel25** [comment]
Okay, that's cool.Thanks!
