### ISSUE TITLE
Create docs for adding mixpanel for tracking events on the app

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#43]
Create a page under docs explaining how to set up site reporting with MixPanel. You can see some examples of how I did this with [Rainbow Stack summit](https://github.com/brittanyjoiner15/rainbowstack-summit). 

Note - we don't want to actually _add_ Mixpanel to this template, but want to layout docs for exactly how someone might do that if they want to track things for their events. For instance, if they want to track how many people fill out a form, visit a page, click a button, etc. 

Ideally the docs will be a single file added to the `docs` folder called `mixpanel.md` and will reference the Mixpanel docs, and give a step by step guide for what needs to be set up on MixPanel, where to initialize it, and how to create events, including some examples.

**Comment by audreymengue** [comment]
Hi @brittanyjoiner15 , I would love to work on it if you would have me.

**Comment by brittanyjoiner15** [comment]
@audreymengue sure! assigning you now!

**Comment by audreymengue** [comment]
Hi @brittanyjoiner15 , if I understand very well, this task is about how to add Mixpanel panel on this template if they want to? Also, the Mixpanel we are referring to is the web analytics tools right?

**Comment by brittanyjoiner15** [comment]
@audreymengue yes that's correct! and yep this tool. https://mixpanel.com/

**Comment by audreymengue** [comment]
Alright. Thank you. On it.
