### ISSUE TITLE
Create light mode option

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#44]
Right now the app is using Eui dark mode. Create a toggle to allow a user to enable light mode. 

You can learn more about how this works with Eui in the docs: https://elastic.github.io/eui/#/theming/theme-provider

Please check the various tabs and components while implementing as this may require some additional configuration on those.

**Comment by NandanVyas** [comment]
Hello ma'am, I want to contribute to it, can you assign me this issue and please provide a suitable location for the toggle button as well ?

**Comment by brittanyjoiner15** [comment]
@NandanVyas great! i'll assign you! I imagine placing it somewhere here, maybe below the buttons? But im open to other locations if you have a better idea!

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/16166290/192851044-b8ac7ae7-4d1e-4548-a757-947408ca68cf.png">

**Comment by Anuran12** [comment]
Hi @brittanyjoiner15 can you assign it to me ?

**Comment by brittanyjoiner15** [comment]
@Anuran12 sorry this has already been assigned, but you're welcome to connect with @NandanVyas if you'd like to pair with them on it!

**Comment by brittanyjoiner15** [comment]
@NandanVyas hey there! have you had a chance to work on this?

**Comment by Anuran12** [comment]
@brittanyjoiner15 hey.... if he would not response.... then could you please assign it to me ?

**Comment by NandanVyas** [comment]
@brittanyjoiner15 yea I have done the work. I am just looking if I can improve it since this will be my first contribution. I have already discussed the looks and position of the button on Twitter with you.

**Comment by brittanyjoiner15** [comment]
@NandanVyas great, thanks for the update! Looking good, just had a few changes requested. Let me know if you need any help with that

**Comment by brittanyjoiner15** [comment]
@NandanVyas saw the PR was closed, let me know if you are stuck on anything!

**Comment by NandanVyas** [comment]
Ok ma’am I will let you know.
