### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by Mannuel25** [brittanyjoiner15/eui-event-template#46]
I'd suggest we have issues templates.
- A custom issue template
- A feature template (this comes in handy since we now have a research notes that tracks technologies/features to be added)

If it's a good suggestion, I'd like to add them.

**Comment by brittanyjoiner15** [comment]
@Mannuel25 thanks for suggesting this but we actually have some issues open for working on this (#16 and #2) and someone assigned to tackle it! Good suggestion though!

**Comment by Mannuel25** [comment]
Oh, my bad. I thought it didn't exist. Thanks
