### ISSUE TITLE
Update the meta data to have a new image and title

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#47]
Update meta data title, image, and description to have a new image and title that relates to updates on the site "identity theft conference". (Will need for [this issue](https://github.com/brittanyjoiner15/eui-event-template/issues/29) to be completed first but should be finished on Oct 1st.)

You'll find the meta data set in this file: https://github.com/brittanyjoiner15/eui-event-template/blob/main/public/index.html#L5

update the: 

* favicon (thumb print image that is the logo in the nav bar)
* OG title 
* OG  description ("Use React and EUI to create an event or conference website! This is a template with an example."
* OG image (hero image used in the main event details tab)
* title ("React and Eui Event Template")
* description ("Use React and EUI to create an event or conference website! This is a template with an example."

**Comment by skyspace88** [comment]
yay! :D

**Comment by brittanyjoiner15** [comment]
@dreymotoh woohoo! just assigned you! lets pair on this next week and go through it!

**Comment by chiragkhatri19** [comment]
Can I work on this with you ? I am pretty much a newbie in open source, So really wanna learn something from experienced contributors

**Comment by brittanyjoiner15** [comment]
@chiragkhatri19 yeah! i'm actually going to pair with @dreymotoh on this and it's a great one to demo how open source contribution can work!

Can you join this slack community? https://join.slack.com/t/build-with-britt/shared_invite/zt-1ew1pk4w7-sVTSOA4QSA1B6kOpMUBE_A

It's a space I've got with me and some other fellow builders and I'm probably going to do some live pairing in there! You're welcome to join when @dreymotoh and i work on this!

**Comment by chiragkhatri19** [comment]
I joined the community, And thanks for helping me contribute, I really want to contribute something valuable to open source in this October.

**Comment by brittanyjoiner15** [comment]
@chiragkhatri19 awesome! i don't see you in there yet, so you might need to confirm something in your email. ill be posting the #general channel when I'm going to be doing some builds, so feel free to watch in there and join whenever!

**Comment by chiragkhatri19** [comment]
For sure @brittanyjoiner15 
I'll confirm the email and wait for that notification. Thanks for having me again
