### ISSUE TITLE
[BUG] Unwanted horizontal scroll

### ISSUE THREAD

**Issue by divyanshraj0408** [brittanyjoiner15/eui-event-template#64]
### The problem:
There is some unwanted horizontal scroll due to overflow problem.

### Solution in my mind:
This can be simply solved by setting margin and padding as 0 for the body but there are other methods too to solve this  issue.

### Screenshots: 
![Screencast from 02-10-22 08!UNITO-UNDERSCORE!34!UNITO-UNDERSCORE!09 AM IST](https://user-images.githubusercontent.com/73312468/193436105-50957c4d-ae0e-42a4-942c-b61115503180.gif)

note: If possible I would like to work on this issue for hacktoberfest :p .

**Comment by brittanyjoiner15** [comment]
@divyanshraj0408 can you check on https://eui-event.vercel.app/ now and see if you still experience this? We just had a PR submitted for addressing that in another issue

**Comment by brittanyjoiner15** [comment]
Closing this for now, but feel free to reopen if you still notice the behaviour!
