### ISSUE TITLE
Upgrade Eui to latest version

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#70]
Need to upgrade Eui to latest version which has several improvements, and fixes a bug with local development that does not consistently render icons. 

@brandonmcconnell would you like this one since you pointed it out in another PR?

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Sure, I'll take this one on! I can try to have that done by early next week. I'll continue syncing upstream in the meantime to avoid any merge conflicts.

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell yes i was going to say make sure you're working on the latest version of main since there's a lot of changes and i can imagine this one would be a real PITA for conflicts 😂

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell do you have a PR for this?

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 No, not yet. This one will likely be a bigger change, and I won't have enough time to look at it until I'm back from traveling next week, so could we free this one up for now? If it's still pending when I'm back, I'd be happy to pick it back up.

**Comment by brittanyjoiner15** [comment]
@brandonmcconnell yep no worries! i will un-assign you for now, and if it's available when you're back you're welcome to grab it!

**Comment by brandonmcconnell** [comment]
@brittanyjoiner15 Thanks!

**Comment by adsingh14** [comment]
@brittanyjoiner15 I checked `.lock` file where EUI current version is `61.0.0` and latest version is `70.0.0`. I would like to update it. Any insights on this?

Update: I upgrade EUI on local server. Everything works as expected except those two changes (point 3 and 4) I mentioned in #121.

**Comment by brittanyjoiner15** [comment]
@adsingh14 just to check you updated it and those things still did not work? 

And nothing broke? If you can please push a PR with those changes, I'll take a look this weekend and run it locally. I am surprised nothing broke 😂 but that would be great!

**Comment by adsingh14** [comment]
@brittanyjoiner15  I will push that change in next PR. I've checked all pages and functionality.

**Comment by adsingh14** [comment]
@brittanyjoiner15 Today, I sync and update Eui to 70 which shows deprecated errors. I fixed it which broke the CSS of some pages.

Icons are rendered offline after upgrade.

**Comment by brittanyjoiner15** [comment]
Closing as i'm unable to maintain this at the moment. Will re-open when i have more bandwidth!
