### ISSUE TITLE
Add Attractive Buttons

### ISSUE THREAD

**Issue by Mahekjain2706** [brittanyjoiner15/eui-event-template#73]
I want to add some attractive buttons using HTML, CSS, and javascript.
By adding some attractive and animated buttons website look more attractive and by hover effect oh button , it looks more user interactive .

**Comment by Mahekjain2706** [comment]
Hey @brittanyjoiner15, I want to work on this task, Can you assign me this task?

**Comment by brittanyjoiner15** [comment]
@Mahekjain2706 so we want to keep using the Eui template and Eui buttons, but as long as you can keep using those and add some custom classes, that should be fine! Please share screenshots before submitting the PR so we can make sure we're aligned!

**Comment by 0xClint** [comment]
Hey, @brittanyjoiner15 is this issue solved? If not, can you assign this to me? I have some ideas.

**Comment by brittanyjoiner15** [comment]
@Mahekjain2706 wanted to check in on this! Have you had a chance to work on it?

**Comment by brittanyjoiner15** [comment]
@Omkar0803 i haven't heard from @Mahekjain2706 so i believe this one is up for grabs. Are you still interested in working on it?

**Comment by 0xClint** [comment]
Yes, @brittanyjoiner15 I would like to contribute!

**Comment by brittanyjoiner15** [comment]
@Omkar0803 assigning you now!

**Comment by brittanyjoiner15** [comment]
@Omkar0803 hey just wanted to check in and see if you had made any updates or needed any help!

**Comment by brittanyjoiner15** [comment]
@Omkar0803 i am unassigning you since I haven't heard anything in a week, but feel free to comment back on here and i will assign again if it's available
