### ISSUE TITLE
Utilize Eui's i18n to add internationalization to the app

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#75]
Configure the app to utilize i18n so that we can make the website work with other languages!

https://elastic.github.io/eui/#/utilities/i18n

**Comment by bpvcode** [comment]
Hello, can you assign this issue to me?
I will investigate this and try to solve the issue :)
I think I can solve this, I will read the docs and let you know about my progress, once this has been attached to me.

Thanks :)

**Comment by sanjanaudar** [comment]
Hi @brittanyjoiner15, I'd be happy to take this one. :)

**Comment by brittanyjoiner15** [comment]
@sanjanaudar awesome! let me know if you have any questions or need any help!

**Comment by brittanyjoiner15** [comment]
@sanjanaudar just wanted to check in on this and see how things are going?

**Comment by sanjanaudar** [comment]
@brittanyjoiner15 It's going slow but steady.

**Comment by brittanyjoiner15** [comment]
@sanjanaudar great! per our guidelines, please post a comment in here every 2 days to let me know the status! if i don't hear from you for a period of more than 2 days, I'll need to reassign, so just keep me posted please!

**Comment by sanjanaudar** [comment]
@brittanyjoiner15 Got it! I won't be able to work on it till next Thursday. If you want to assign it to someone else. 
If its still available then I can it up again.

**Comment by brittanyjoiner15** [comment]
@sanjanaudar ah understandable! i will unassign it for now, but i don't think I've seen much interest in yet, so it very well may remain available! Just let me know when you're ready to work on it and I'll assign you right away!

**Comment by mendex94** [comment]
Hi, I'd be like to give it a try! Can you assign this to me?

**Comment by brittanyjoiner15** [comment]
@mendex94 yes I can assign to you! Let me know if you need any help, and please check in here within a couple days with a progress update so i know you're still interested!

**Comment by mendex94** [comment]
@brittanyjoiner15 Thanks, I'll start monday!

**Comment by brittanyjoiner15** [comment]
@mendex94 just wanted to check if you have an update on this!

**Comment by brittanyjoiner15** [comment]
@mendex94 going to unassign you since it's been 2 weeks since we've heard from you, but feel free to comment in here and grab it again if you want to work on it and it's available!

**Comment by asma-mughal** [comment]
Hey, I'd be like to give it a try. Can anyone assign this to me?

**Comment by brittanyjoiner15** [comment]
hey @asma-mughal ! yes ill assign you!

**Comment by asma-mughal** [comment]
> hey @asma-mughal ! yes ill assign you!

working on it.

**Comment by brittanyjoiner15** [comment]
@asma-mughal thanks for the update!

**Comment by asma-mughal** [comment]
I have configured the translations of an app using i18next instead of i18n Elastic UI, is it wrong? Do I have to change the whole code?

**Comment by brittanyjoiner15** [comment]
@asma-mughal i am not familiar with i18next but if you are able to use that and it works, then that is fine with me!

**Comment by asma-mughal** [comment]
Yes I am totally familiar with it and I am done half of the project using i18next. Thank you for the reply.

**Comment by brittanyjoiner15** [comment]
@asma-mughal perfect!
