### ISSUE TITLE
Translate key text in app to Spanish

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#76]
After we have a i18n available, then we'll want to be able to translate key parts of the app. If you speak Spanish and would feel comfortable translating the key text, that would be great!

This is what we need translated: 

* tab titles
  * `Event Details`
  * `Speakers`
  * `Talks`
  * `Recordings`
  * `FAQs/Frequently Asked Questions`
* Calendar Button text: `Save the {date} session`
* Second button text:
  * `Sign up for updates`
  * `Join the slack group`
* Button on talks page text:  `Show times in EDT` and `Show times in Local`

**Comment by jbarbaran** [comment]
Hi there, I'm a native Spanish speaker, and I would like to tackle this issue! Can you assign me to it?

**Comment by brittanyjoiner15** [comment]
@jbarbaran yes! will do! in your PR, can you add a file that looks like this? 

name: `es.json`

and format is 
```
{
  "eventDetails": "Spanish translation of it",
  "speakers": "translation",
  "talks": "",
  ... etc
}

```

**Comment by jbarbaran** [comment]
Quick question @brittanyjoiner15 , the file es.json should be located in any particular path or folder?

**Comment by brittanyjoiner15** [comment]
@jbarbaran good question! can you create a folder at the root called `translations` and then place it in there?

**Comment by domstrozynski** [comment]
Hi @brittanyjoiner15  , if you need Polish translation I could be of use 😃

**Comment by brittanyjoiner15** [comment]
@domstrozynski sure!! Can you create an issue for it and I'll assign it!
