### ISSUE TITLE
Translate key text in app to German

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#78]
After we have a i18n available, then we'll want to be able to translate key parts of the app. If you speak German and would feel comfortable translating the key text, that would be great!

This is what we need translated: 

* tab titles
  * `Event Details`
  * `Speakers`
  * `Talks`
  * `Recordings`
  * `FAQs/Frequently Asked Questions`
* Calendar Button text: `Save the {date} session`
* Second button text:
  * `Sign up for updates`
  * `Join the slack group`
* Button on talks page text:  `Show times in EDT` and `Show times in Local`

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi, @brittanyjoiner15 what if I convert it using google and place them in your translation file what do you say about that?

**Comment by brittanyjoiner15** [comment]
@Muhammad-Shahid-Jamal i would prefer someone who speaks German Google isn't always very reliable. If you know someone who does and could ask them for the translations and then you implement the file with their translations, that would be great! But my preference is something more credible than Google

**Comment by m1ga** [comment]
@brittanyjoiner15 I can help you there if you like

**Comment by brittanyjoiner15** [comment]
@m1ga that would be great thanks!!

**Comment by m1ga** [comment]
There is no structure, folder or english template. So should I use the elements form the Spanish translation? How to test it? Those IDs aren't use in the app

**Comment by m1ga** [comment]
If you have a different structure let me know. Would be better to add the translation methods first before creating the language files ;-)

**Comment by brittanyjoiner15** [comment]
@m1ga great question! we have another issue open for actually setting up i18n but as you pointed out, the tokens don't quite exist yet. 

If you can just make a `de.json` file in the `Translations` folder  that is templated like this:

```
{
  "eventDetails": "German translation of it",
  "speakers": "translation",
  "talks": "",
  ... etc
}
```


That would be great! See an example of the Spanish one here: 
https://github.com/brittanyjoiner15/eui-event-template/blob/main/Translations/es.json

**Comment by brittanyjoiner15** [comment]
@m1ga ah just saw your PR! yes exactly like that! Perfect

**Comment by m1ga** [comment]
@brittanyjoiner15 quickly added a clean-up PR https://github.com/brittanyjoiner15/eui-event-template/pull/82 so other translators have an easier job ;-)

**Comment by brittanyjoiner15** [comment]
I appreciate the pro-activeness! Just merged that in
