### ISSUE TITLE
Create an accessibility checklist

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#79]
Add a section to the bottom of the  https://github.com/brittanyjoiner15/eui-event-template/blob/main/docs/research-notes.md file with a checklist of things that we should consider for improving accessibility on the site.

Ideally, you will make a checklist and then :white_check_mark: off any items the site is already doing well with, and then mention any areas that we specifically need to improve so that we can easily convert those into issues for people to tackle.

**Comment by Nasimmhn** [comment]
Hi @brittanyjoiner15 
I like to work on this task, Can you assign me this task?

**Comment by bpvcode** [comment]
Hello, can I work on this issue? :)

**Comment by brittanyjoiner15** [comment]
@bpvcode yes! assigning you now!

**Comment by 0xClint** [comment]
hey, can I also contribute to this issue?

**Comment by brittanyjoiner15** [comment]
@bpvcode hey just wanted to check on this! Have you made any progress on it or are you stuck with anything?

**Comment by brittanyjoiner15** [comment]
@Omkar0803 this has been assigned to @bpvcode but you're welcome to coordinate with them, or if I do not hear from them by tomorrow, it will be up for re-assignment, so you're welcome to respond back on Thursday if they have not posted

**Comment by varunsood2003** [comment]
Hey I'm new to open source contribution but would love to work and learn with you can you assign me a issue ?

**Comment by bpvcode** [comment]
Hello @brittanyjoiner15, I'm working on this :)
I'm making a list of things that we should take care of, and after that, I will suggest implementing a technology that can analyze each PR and give us a report on different topics, accessibility is one of them.
But I think this should be done in another Issue :)
Probably tonight or tomorrow I will do the MR :)

**Comment by brittanyjoiner15** [comment]
@varunsood2003 please check for unassigned issues, or create one if you have an idea of something that will improve the site!

**Comment by brittanyjoiner15** [comment]
@bpvcode that's great! I agree - feel free to create another issue for the automation piece on PRs. thanks!
