### ISSUE TITLE
Add a Banner for the Header of Readme File

### ISSUE THREAD

**Issue by chiragkhatri19** [brittanyjoiner15/eui-event-template#86]
Hello Everyone, I am Graphics Designer too, So thought why not to contribute a Minimal Banner for the Readme File.

**Comment by brittanyjoiner15** [comment]
@chiragkhatri19 assigned!

**Comment by chiragkhatri19** [comment]
Hey @brittanyjoiner15  Can you add Hacktoberfest Labels to it please
