### ISSUE TITLE
Need a favicon image

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#88]
Need a new favicon to replace the rainbow image. If we can stay on theme for the identity theft conference that would be awesome!

**Comment by chiragkhatri19** [comment]
Already here @brittanyjoiner15

**Comment by brittanyjoiner15** [comment]
In the PR if you can just delete the original `favicon.ico` file and add the new one with the same name, that would be great, so we don't need to update any references to it.

**Comment by 0xClint** [comment]
Hey can you assign this to me, I can make the favicon image

**Comment by brittanyjoiner15** [comment]
@Omkar0803 sorry this one also should have been closed as it's been completed. So sorry about that!
