### ISSUE TITLE
Edit the Pull Request Template 

### ISSUE THREAD

**Issue by chiragkhatri19** [brittanyjoiner15/eui-event-template#90]
Edit it by removing the Assignee and Reviewer Lines

**Comment by brittanyjoiner15** [comment]
Something else i would like to include, is if we can specify to say "fixes {link to issue}" so that it will automatically close that issue when i merge the PR

**Comment by 0xClint** [comment]
Hey is this issue solved?

**Comment by brittanyjoiner15** [comment]
@Omkar0803 yes it has! sorry need to close it.
