### ISSUE TITLE
Join the Slack Group!

### ISSUE THREAD

**Issue by SahilAnower** [brittanyjoiner15/eui-event-template#95]
### Hey brittanyjoiner15 , do we have the slack group available? If yes , then we can redirect users to the slack group link, where they can join in immediately! 
> I am interested to work on this

**Comment by brittanyjoiner15** [comment]
@SahilAnower this is something that will be customized for each person who uses the template, so it's intentionally left with a `#` / blank URL so people can customize it. Thanks for checking though!
